<div class="modal fade connexion" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="post" action="index.php?page=connexion" class="visible-xs">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title persoTitle">Se connecter</h3>
                </div>
                <div class="modal-body">
                <?php if($pseudo == false):?>
                    <div class="form-group has-error">
                        <input type="text" class="form-control input-sm" id="pseudo" name="pseudo" placeholder="Pseudo erroné">
                    </div>
                <?php else:?>
                    <div class="form-group">
                        <input type="text" class="form-control input-sm" id="pseudo" name="pseudo" placeholder="Pseudo">
                    </div>
                <?php endif;?>
                <?php if($password == false):?>
                    <div class="form-group has-error">
                        <div class="input-group">
                            <input type="password" class="form-control input-sm" id="password" name="password" placeholder="Mot de passe erroné">
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-sm" type="submit">       
                                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                    </div>
                <?php else:?>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="password" class="form-control input-sm" id="password" name="password" placeholder="Mot de passe">
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-sm" type="submit">       
                                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                    </div>
                <?php endif;?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default">Valider</button>
                </div>
            </form>   
        </div>
    </div>
</div>