
<nav class="navbar navbar-default navbar-static-bottom">
    <div class="container-fluid">
        <div class="navbar-header navbar-left">
            <a class="navbar-brand" href="index.php">
                <img class="logo" alt="" src="images/logo/logo.png">
            </a>
            <a class="navbar-brand" href="index.php">
            Le Petit Matelot
            </a>
        </div>
        <ul class="nav navbar-nav navbar-left">
            <li><a href="index.php?page=registration">Inscription</a></li>
            <li><a href="index.php?page=contact">Contact</a></li>
        </ul>
        <div class="navbar-form navbar-right">
            <button type="submit" class="btn btn-default" data-toggle="modal" data-target="#myModal">Mentions légales</button>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title" id="myModalLabel">Mentions légales</h4>
                        </div>
                        <div class="modal-body">
                            <p>Le site web "lepetitmatelot.com" est hébergé chez OVH :</p>
                            <address>
                            <strong>SAS OVH</strong><br>
                            2 rue Kellermann - BP 80157<br>
                            59 100 Roubaix<br>
                            Phone: +33 9 72 10 10 07<br>
                            Web: http://www.ovh.com<br>
                            </address>
                            <p class="text-justify">Les informations recueillies sur ce site web sont enregistrées dans un fichier informatisé par Le Petit Matelot pour que les utilisateurs inscrits puissent accéder aux fonctionnalités avancées de la plateforme web "lepetitmatelot.com". Notamment, laisser leur avis et des commentaires sur un port de plaisance référencé sur Le Petit Matelot.</p>
                            <p class="text-justify">Elles sont conservées pendant 1 an et sont destinées à l'administrateur du site "lepetitmatelot.com".</p>
                            <p class="text-justify">Conformément à la loi « informatique et libertés », vous pouvez exercer votre droit d'accès aux données vous concernant et les faire rectifier en contactant : contact@lepetitmatelot.com</p>
                            <p class="text-justify">Nous vous informons de l’existence de la liste d'opposition au démarchage téléphonique « Bloctel », sur laquelle vous pouvez vous inscrire ici : https://conso.bloctel.fr/</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-right">
            <p class="navbar-text">
                <i class="fa fa-copyright" aria-hidden="true"></i>
                Copyright 2017 - Le Petit Matelot
            </p>
        </div>
    </div> 
</nav>
<script src="js/jquery.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="js/sharemysea.js"></script>
<script>
$(function () {
    
    $('[data-toggle="popover"]').popover();
         
});
</script>
<script src="bootstrap/js/bootstrap.min.js"></script>
<script src="js/ranking.js"></script>
<script src="js/animation.js"></script>
<script src="js/comment.js"></script>
<script src="js/analyticstracking.js"></script>
</body>
</html>