<div class="modal fade news" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                </button>
                <h3 class="modal-title persoTitle">Les news du Petit Matelot...</h3>
            </div>
            <div class="modal-body">
            <?php foreach($news as $key => $value):?>
                <div class="list-group">
                    <a href="<?= $value['url']?>" target="_blank" class="list-group-item">
                        <h4 class="list-group-item-heading persoTitle"><?= $value['title']?></h4>
                        <p class="list-group-item-text"><?= $value['content']?></p>
                        <p class="text-right date"><?= $value['dateForm']?></p>
                    </a>
                </div>
            <?php endforeach;?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>