<?php if($pageActuelle == 1):?>
    <li class="disabled">
        <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
<?php else:?>
    <li>
        <a href="index.php?page=port&pageNumber=<?=$pageActuelle-1?>&id=<?=$_GET['id']?>" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>                                        
<?php endif;?>
<?php for($i=1; $i<=$number_of_pages; $i++):?>
    <?php if($i == $pageActuelle):?>
        <li class="active">
            <a href="index.php?page=port&pageNumber=<?=$i?>&id=<?=$_GET['id']?>"><?=$i?></a>
        </li>
    <?php else:?>
        <li>
            <a href="index.php?page=port&pageNumber=<?=$i?>&id=<?=$_GET['id']?>"><?=$i?></a>
        </li>
    <?php endif;?>
<?php endfor;?>
<?php if($pageActuelle == $number_of_pages OR $number_of_pages == 0):?>
    <li class="disabled">
        <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
<?php else:?>
    <li>
        <a href="index.php?page=port&pageNumber=<?=$pageActuelle+1?>&id=<?=$_GET['id']?>#posts" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
<?php endif;?>