<main class="container-fluid">
    <header class="page-header" data-harbour="<?= $harbour['harbour']?>">
        <h1>
            Port <?= $harbour['harbour']?>
            <span class="rank"><?= $rank_global?></span>
            <small class="hidden-xs"><?= $harbour['slogan']?> !</small>
            <span class="starsHeader hidden-xs"><?= $stars[$avis_global]?></span>
        </h1>
        <h2 class="visible-xs"><?= $stars[$avis_global]?></h2>
        <?php require 'iconesServices.phtml';?>
    </header>
    <section class="row">
        <div class="col-sm-6 col-lg-5">
            <div class="row">
                <article id="introduction" class="col-sm-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">Présentation </h3>
                        </div>
                        <div class="panel-body">
                            <p class="text-justify"><?= $harbour['introduction']?></p>
                        </div>
                    </div>
                </article>
            </div>
        </div>
        <article id="ranking" class="col-lg-3 visible-lg-block">
            <?php require 'ranking.phtml';?>
        </article>
        <article id="imagePort" class="col-sm-6 col-lg-4">
            <div id="carousel" class="carousel slide hidden-xs" data-ride="carousel" data-interval="false">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel" data-slide-to="1"></li>
                    <li data-target="#carousel" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="images/ports/<?= $harbour['image1']?>" alt="...">
                    </div>
                    <div class="item">
                        <img src="images/ports/<?= $harbour['image2']?>" alt="...">
                    </div>
                    <div class="item">
                        <img src="images/ports/<?= $harbour['image3']?>" alt="...">
                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </article>
    </section>
    <section class="row">
        <div class="hidden-xs col-sm-6">
            <?php require 'view/formPost.phtml';?>
            <article id="posts" class="hidden-lg">
                <?php $screen='md';?>
                <?php require 'view/lastPosts.phtml';?>        
            </article>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <article id="ranking" class="hidden-lg col-xs-12">
                    <?php require 'view/ranking.phtml';?>    
                </article>
            </div>
            <div class="row">
                <?php if(empty($strength['strength1']) & empty($strength['strength2']) & empty($strength['strength3']) & empty($strength['strength4']) & empty($strength['strength5'])):?>
                <?php else:?>
                    <article id="strength" class="col-sm-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title text-center">Points forts</h3>
                            </div>
                            <div class="list-group">
                                <?php if(!empty($strength['strength1'])):?>
                                    <li class="list-group-item">
                                        <i class="fa fa-plus-circle" aria-hidden="true"></i>  
                                        <?= $strength['strength1']?>  
                                    </li>
                                <?php endif;?>
                                <?php if(!empty($strength['strength2'])):?>
                                    <li class="list-group-item">
                                        <i class="fa fa-plus-circle" aria-hidden="true"></i>  
                                        <?= $strength['strength2']?>
                                    </li>
                                <?php endif;?>
                                <?php if(!empty($strength['strength3'])):?>
                                    <li class="list-group-item">
                                        <i class="fa fa-plus-circle" aria-hidden="true"></i> 
                                        <?= $strength['strength3']?>
                                    </li>
                                <?php endif;?>
                                <?php if(!empty($strength['strength4'])):?>
                                    <li class="list-group-item">
                                        <i class="fa fa-plus-circle" aria-hidden="true"></i>  
                                        <?= $strength['strength4']?>
                                    </li>
                                <?php endif;?>
                                <?php if(!empty($strength['strength5'])):?>
                                    <li class="list-group-item">
                                        <i class="fa fa-plus-circle" aria-hidden="true"></i>  
                                        <?= $strength['strength5']?>
                                    </li>
                                <?php endif;?>
                            </div>
                        </div> 
                    </article>
                <?php endif;?>
                <?php if(empty($weakness['weakness1']) & empty($weakness['weakness2']) & empty($weakness['weakness3']) & empty($weakness['weakness4']) & empty($weakness['weakness5'])):?>
                <?php else:?>
                    <article id="weakness" class="col-sm-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title text-center">Points faibles</h3>
                            </div>
                        <div class="list-group">
                            <?php if(!empty($weakness['weakness1'])):?>
                                <li class="list-group-item">
                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>  
                                    <?= $weakness['weakness1']?>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($weakness['weakness2'])):?>
                                <li class="list-group-item">
                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>  
                                    <?= $weakness['weakness2']?>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($weakness['weakness3'])):?>
                                <li class="list-group-item">
                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>  
                                    <?= $weakness['weakness3']?>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($weakness['weakness4'])):?>
                                <li class="list-group-item">
                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>  
                                    <?= $weakness['weakness4']?>
                                </li>
                            <?php endif;?>
                            <?php if(!empty($weakness['weakness5'])):?>
                                <li class="list-group-item">
                                    <i class="fa fa-minus-circle" aria-hidden="true"></i>  
                                    <?= $weakness['weakness5']?>
                                </li>
                            <?php endif;?>
                        </div>
                    </div> 
                </article>
            <?php endif;?>
            </div>  
        </div>
    </section>
    <section class="row visible-xs-block">
    <?php require 'view/formPost.phtml';?>
        <article id="posts" class="col-xs-12">
            <?php $screen='xs';?>
            <?php require 'view/lastPosts.phtml';?>
        </article>
    </section>
    <section class="row visible-lg-block" id="postsLg">
        <article id="posts" class="col-sm-12 col-lg-12">
            <?php $screen='lg';?>
            <?php require 'view/lastPosts.phtml';?> 
        </article>
    </section>
</main>
